name: Rust Bindings (Linux)

on:
  workflow_dispatch:

jobs:
  ci:
    name: Compile, Build and Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rust Toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.64.0
      - run: rustup component add rustfmt

      - name: Cache deps
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ steps.rust-toolchain.outputs.rustc_hash }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Execute cargo test
        run: |
          cd rust
          cargo test

      - name: Execute build scripts
        run: bash ./scripts/build_linux.sh

      - name: Run binding/crypto tests
        run: flutter test

      - name: Run uncleaned git update
        run: git fetch origin && git merge --ff-only --strategy-option ours

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (Linux) Bindings

      - name: Run if changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create Pull Request
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update build bindings for linux
          title: 'Update build bindings for linux'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          branch: main
          labels: automerge, automated pr

      - name: Run if no changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
